Song.destroy_all
Album.destroy_all
Artist.destroy_all

zepp = Artist.create(name: "Led Zeppelin")
nirvana = Artist.create(name: "Nirvana")
kanye = Artist.create(name: "Kanye")
fjm = Artist.create(name: "Father John Misty")
bk = Artist.create(name: "The Black Keys")
gorillaz = Artist.create(name: "Gorillaz")
magrog = Artist.create(name: "Maggie Rogers")
joji = Artist.create(name: "Joji")
ah = Artist.create(name: "Astra Heights")


lz = Album.create( title: "Led Zeppelin", release_date: 1969, artist_id: zepp.id, artwork: "https://images-na.ssl-images-amazon.com/images/I/51SUWsbmnHL._SX466_.jpg")
    Song.create( name: "Good Times Bad Times", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "Babe I'm Gonna Leave You", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "You Shook Me", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "Dazed and Confused", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "Your Time is Gonna Come", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "Black Mountain Side", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "Communication Breakdown", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "I Can't Quit You Baby", album_id: lz.id, artist_id: zepp.id )
    Song.create( name: "How Many More Times", album_id: lz.id, artist_id: zepp.id )

lzII = Album.create( title: "Led Zeppelin II", release_date: 1969, artist_id: zepp.id, artwork: 'https://images-na.ssl-images-amazon.com/images/I/81Uzjt5J5jL._SX355_.jpg')
    Song.create( name: "Whole Lotta Love", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "What Is and What Should Never Be", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "The Lemon Song", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "Thank You", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "Heartbreaker", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "Living Loving Maid", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "Ramble On", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "Moby Dick", album_id: lzII.id, artist_id: zepp.id )
    Song.create( name: "Bring It on Home", album_id: lzII.id, artist_id: zepp.id )

lzIII = Album.create( title: "Led Zeppelin III", release_date: 1970, artist_id: zepp.id, artwork: 'https://img.discogs.com/mhUBAaTFbj-QdHzmVkIP9_rv240=/fit-in/600x588/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-5743324-1401645059-8235.jpeg.jpg' )
    Song.create( name: "Immigrant Song", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Friends", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Celebration Day", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Since I've Been Loving You", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Out on the Tiles", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Gallows Pole", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Tangerine", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "That's the Way", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Bron-Y-Aur-Stomp", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Hats Off to (Roy) Harper", album_id: lzIII.id, artist_id: zepp.id )

lzIV = Album.create( title: "Led Zeppelin IV", release_date: 1971, artist_id: zepp.id, artwork: 'https://i.pinimg.com/originals/ca/08/e6/ca08e626b86494e244649e60da425c65.jpg' )
    Song.create( name: "Black Dog", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Rock and Roll", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "The Battle of Evermore", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Stairway to Heaven", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Misty Mountain Hop", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Four Sticks", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "Going to California", album_id: lzIII.id, artist_id: zepp.id )
    Song.create( name: "When the Levee Breaks", album_id: lzIII.id, artist_id: zepp.id )

bleach = Album.create( title: "Bleach", release_date: 1989, artist_id: nirvana.id, artwork: "https://i.pinimg.com/originals/aa/e9/47/aae947e0fa805fb23934781ed1b6b2da.png")
    Song.create( name: "Blew", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Floyd The Barber", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "About A Girl", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "School", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Love Buzz", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Paper Cuts", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Negative Creep", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Scoff", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Swap Meat", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Mr. Moustache", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Sifting", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Big Cheese", album_id: bleach.id, artist_id: nirvana.id )
    Song.create( name: "Downer", album_id: bleach.id, artist_id: nirvana.id )

nevermind = Album.create( title: "Nevermind", release_date: 1991, artist_id: nirvana.id, artwork: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2016%2F09%2F000125503.jpg&q=85")
    Song.create( name: "Smells Like Teen Spirit", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "In Bloom", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Come As You Are", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Breed", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Lithium", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Polly", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Territorial Pissings", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Drain You", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Lounge Act", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Stay Away", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "On A Plain", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Something In The Way", album_id: nevermind.id, artist_id: nirvana.id )
    Song.create( name: "Endless, Nameless", album_id: nevermind.id, artist_id: nirvana.id )

utero = Album.create( title: "In Utero", release_date: 1993, artist_id: nirvana.id, artwork: "https://images-na.ssl-images-amazon.com/images/I/710XKXHIeNL._SL1400_.jpg")
    Song.create( name: "Serve the Servants", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Scentless Apprentice", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Heart-Shaped Box", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Rape Me", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Frances Farmer Will Have Her Revenge on Seattle", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Dumb", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Very Ape", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Milk It", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Pennyroyal Tea", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Radio Friendly Unit Shifter", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "Tourette's", album_id: utero.id, artist_id: nirvana.id )
    Song.create( name: "All Apologies", album_id: utero.id, artist_id: nirvana.id )

fearfun = Album.create( title: "Fear Fun", release_date: 2012, artist_id: fjm.id, artwork: "https://media.pitchfork.com/photos/5929b52f5e6ef95969322720/1:1/w_600/b6c57579.jpeg")
    Song.create( name: "Funtimes in Babylon", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Nancy From Now On", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Hollywood Forever Cemetery Sings", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "I'm Writing a Novel", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "O I Long to Feel Your Arms Around Me", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Misty's Nightmares 1 & 2", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Only Son of the Ladiesman", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "This Is Sally Hatchet", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Well, You Can Do It Without Me", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Now I'm Learning to Love the War", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Tee Pees 1-12", album_id: fearfun.id, artist_id: fjm.id )
    Song.create( name: "Everyman Needs a Companion", album_id: fearfun.id, artist_id: fjm.id )


honeybear = Album.create( title: "I Love You, Honeybear", release_date: 2015, artist_id: fjm.id, artwork: "https://media.pitchfork.com/photos/5929abe85e6ef95969321827/1:1/w_600/8a2cb994.jpg")
    Song.create( name: "I Love You, Honeybear", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "Chateau Lobby 4", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "True Affection", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "The Night Josh Tillman Came To Our Apt.", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "When You're Smiling And Astride Me", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "Nothing Good Ever Happens At The Goddamn Thirsty Crow", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "Strange Encounter", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "The Ideal Husband", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "Bored In The USA", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "Holy Shit", album_id: honeybear.id, artist_id: fjm.id )
    Song.create( name: "I Went To The Store One Day", album_id: honeybear.id, artist_id: fjm.id )


purecomedy = Album.create( title: "Pure Comedy", release_date: 2017, artist_id: fjm.id, artwork: "https://media.pitchfork.com/photos/5929c216c0084474cd0c3404/1:1/w_600/a970e645.jpg")
    Song.create( name: "Pure Comedy", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Total Entertainment Forever", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Things It Would Have Been Helpful to Know Before the Revolution", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Ballad of the Dying Man", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Birdie", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Leaving LA", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "A Bigger Paper Bag", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "When the God of Love Returns There'll Be Hell to Pay", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Smoochie", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "Two Wildly Different Perspectives", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "The Memo", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "So I'm Growing Old on Magic Mountain", album_id: purecomedy.id, artist_id: fjm.id )
    Song.create( name: "In Twenty Years or So", album_id: purecomedy.id, artist_id: fjm.id )

gfc = Album.create( title: "God' Favorite Customer", release_date: 2018, artist_id: fjm.id, artwork: "https://media.pitchfork.com/photos/5afb000a846bf02b4c448b2f/1:1/w_600/Father%20John%20Misty:%20God%E2%80%99s%20Favorite%20Customer.jpg")
    Song.create( name: "Hangout at the Gallows", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "Mr. Tillman", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "Just Dumb ENough to Try", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "Date Night", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "Please Don't Die", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "The Palace", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "Disappointing Diamonds Are the Rarest of Them All", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "God's Favorite Customer", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "The Songwriter", album_id: gfc.id, artist_id: fjm.id )
    Song.create( name: "We're Only People", album_id: gfc.id, artist_id: fjm.id )

bro = Album.create( title: "Brothers", release_date: 2010, artist_id: bk.id, artwork: "https://img.discogs.com/KcpWkT0bjvEsnpIIzvxExhTNLIQ=/fit-in/595x595/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2276858-1391418145-8752.jpeg.jpg")
    Song.create( name: "Everlasting Light", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Next Girl", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Tighten Up", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Howlin' For You", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "She's Long Gone", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Black Mud", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "The Only One", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Too Afraid to Love You", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Ten Cent Pistol", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Sinister Kid", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "The Go Getter", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "I'm Not the One", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Unknown Brother", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "Never Gonna Give You Up", album_id: bro.id, artist_id: bk.id )
    Song.create( name: "These Days", album_id: bro.id, artist_id: bk.id )
    
elc = Album.create( title: "El Camino", release_date: 2011, artist_id: bk.id, artwork: "https://images-na.ssl-images-amazon.com/images/I/810GnasrfjL._SL1004_.jpg")
    Song.create( name: "Lonely Boy", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Dead and Gone", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Gold on the Ceiling", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Little Black Submarines", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Money Maker", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Run Right Back", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Sister", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Hell of a Season", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Stop Stop", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Nova Baby", album_id: elc.id, artist_id: bk.id )
    Song.create( name: "Mind Eraser", album_id: elc.id, artist_id: bk.id )

    
turnblue = Album.create( title: "Turn Blue", release_date: 2014, artist_id: bk.id, artwork: "https://images-na.ssl-images-amazon.com/images/I/81iT7jTQJjL._SY355_.jpg")
    Song.create( name: "Weight of Love", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "In Time", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "Turn Blue", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "Fever", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "Year in Review", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "Bullet in the Brain", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "It's Up to You Now", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "Waiting on Words", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "10 Lovers", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "In Our Prime", album_id: turnblue.id, artist_id: bk.id )
    Song.create( name: "Gotta Get Away", album_id: turnblue.id, artist_id: bk.id )

letsrock = Album.create( title: "Let's Rock", release_date: 2019, artist_id: bk.id, artwork: "https://media.pitchfork.com/photos/5d029e94f605603ca64d38ca/1:1/w_600/letsrock_blackkeys.jpg")
    Song.create( name: "Shine A Little Light", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Eagle Birds", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Lo/Hi", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Walk Across The Water", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Tell Me Lies", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Every Little Thing", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Get Yourself Together", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Sit Around And Miss You", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Go", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Breaking Down", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Under The Gun", album_id: letsrock.id, artist_id: bk.id )
    Song.create( name: "Fire Walk With Me", album_id: letsrock.id, artist_id: bk.id )

gorilla = Album.create( title: "Gorillas", release_date: 2001, artist_id: gorillaz.id, artwork: "https://upload.wikimedia.org/wikipedia/en/4/41/GorillazAlbum.jpg")
    Song.create( name: "Re-Hash", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "5/4", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Tomorrow Comes Today", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "New Genious", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Clint Eastwood", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Man Research", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Punk", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Sound Check", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Double Bass", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Rock the House", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "19-2000", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Latin Simone", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Starshine", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "Slow Country", album_id: gorilla.id, artist_id: gorillaz.id )
    Song.create( name: "M1 A1", album_id: gorilla.id, artist_id: gorillaz.id )

demondays = Album.create( title: "Demon Days", release_date: 2005, artist_id: gorillaz.id, artwork: "https://upload.wikimedia.org/wikipedia/en/d/df/Gorillaz_Demon_Days.PNG")
    Song.create( name: "Intro", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Last Living Souls", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Kids With Guns", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "O Green World", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Dirty Harry", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Feel Good Inc.", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "El Mañana", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Every Planet We Reach Is Dead", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "November Has Come", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "All Alone", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "White Light", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "DARE", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Fire Coming out of the Monkey's Head", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Don't Get Lost in Heaven", album_id: demondays.id, artist_id: gorillaz.id )
    Song.create( name: "Demon Days", album_id: demondays.id, artist_id: gorillaz.id )

plasticbeach = Album.create( title: "Plastic Beach", release_date: 2010, artist_id: gorillaz.id, artwork: "https://upload.wikimedia.org/wikipedia/en/d/d1/Plasticbeach452.jpg")
    Song.create( name: "Orchestral Intro", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Welcome to the World of the Plastic Beach", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "White Flag", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Rhinestone Eyes", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Stylo", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Superfast Jellyfish", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Empire Ants", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Glitter Freeze", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Some Kind of Nature", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "On Melancholy Hill", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Broken", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Sweepstakes", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Plastic Beach", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "To Binge", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Cloud of Unknowing", album_id: plasticbeach.id, artist_id: gorillaz.id )
    Song.create( name: "Pirate Jet", album_id: plasticbeach.id, artist_id: gorillaz.id )

humanz = Album.create( title: "Humanz", release_date: 2017, artist_id: gorillaz.id, artwork: "https://upload.wikimedia.org/wikipedia/en/a/a6/HumanzGorillaz.png")
    Song.create( name: "Intro: I Switched My Robot Off", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Ascension", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Strobelite", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Saturnz Barz", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Momentz", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Interlude: The Non-Conformist Oath", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Submission", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Charger", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Interlude: Elevator Going Up", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Andromeda", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Busted and Blue", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Interlude: Talk Radio", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Carnival", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Let Me Out", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Interlude: Penthouse", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Sex Murder Party", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "She's My Collar", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Interlude: The Elephant", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "Hallelujah Money", album_id: humanz.id, artist_id: gorillaz.id )
    Song.create( name: "We Got the Power", album_id: humanz.id, artist_id: gorillaz.id )

hiiapl = Album.create( title: "Heard It In A Past Life", release_date: 2019, artist_id: magrog.id, artwork: "https://media.pitchfork.com/photos/5c361b06a53f2f2c86750925/1:1/w_600/Maggie%20Rogers_Heard%20it%20in%20a%20past%20life.jpg")
    Song.create( name: "Give A Little", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Overnight", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "The Knife", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Alaska", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Light On", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Past Life", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Say It", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "On + Off", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Fallingwater", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Retrograde", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Burning", album_id: hiiapl.id, artist_id: magrog.id )
    Song.create( name: "Back In My Body", album_id: hiiapl.id, artist_id: magrog.id )

tongues = Album.create( title: "In Tongues", release_date: 2018, artist_id: joji.id, artwork: "")
    Song.create( name: "Will He", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "Pills", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "Demons", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "Window", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "Bitter Fuck", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "Worldstar Money (Interlude)", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "Plastic Taste", album_id: tongues.id, artist_id: joji.id )
    Song.create( name: "I Don't Want To Waste My Time", album_id: tongues.id, artist_id: joji.id )

ballads = Album.create( title: "BALLADS1", release_date: 2018, artist_id: joji.id, artwork: "")
    Song.create( name: "ATTENTION", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "SLOW DANCING IN THE DARK", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "TEST DRIVE", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "WANTED U", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "CAN'T GET OVER YOU", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "YEAH RIGHT", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "WHY AM I STILL IN LA", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "NO FUN", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "COME THRU", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "R.I.P.", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "XNXX", album_id: ballads.id, artist_id: joji.id )
    Song.create( name: "I'LL SEE YOU IN 40", album_id: ballads.id, artist_id: joji.id )

nectar = Album.create( title: "Nectar", release_date: 2020, artist_id: joji.id, artwork: "")
    Song.create( name: "Ew", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "MODUS", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Tick Tock", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Daylight", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Upgrade", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Gimme Love", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Run", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Sanctuary", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "High Hopes", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "NITROUS", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Pretty Boy", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Normal People", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "After Thought", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Mr. Hollywood", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "777", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Reanimator", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Like You Do", album_id: nectar.id, artist_id: joji.id )
    Song.create( name: "Your Man", album_id: nectar.id, artist_id: joji.id )

gp = Album.create( title: "Good Problems", release_date: 2007, artist_id: ah.id, artwork: "https://m.media-amazon.com/images/I/61N5I9rZ8GL._SS500_.jpg")
    Song.create( name: "Good People", album_id: gp.id, artist_id: ah.id )
    Song.create( name: "The March", album_id: gp.id, artist_id: ah.id )
    Song.create( name: "The Whole World Changes", album_id: gp.id, artist_id: ah.id )
    Song.create( name: "It's Alright", album_id: gp.id, artist_id: ah.id )
    Song.create( name: "Call To The Underground", album_id: gp.id, artist_id: ah.id )
    Song.create( name: "Greg The Illuminator", album_id: gp.id, artist_id: ah.id )
    